## Remove all files generated by TAF

require(icesTAF, quietly=TRUE)

unlink("db", recursive=TRUE)
unlink("input", recursive=TRUE)
unlink("model", recursive=TRUE)

ftp <- "../../../ftp/wgnssk/2016/ple-eche/"
unlink(paste0(ftp,"input"), recursive=TRUE)
unlink(paste0(ftp,"output"), recursive=TRUE)

dir.remove("../../../ftp", recursive=TRUE)
